version: "3.8"

services:
  app:
    image: ghcr.io/unobserved-io/furtherance-sync:latest
    ports:
      - "8662:8662"
    environment:
      - POSTGRES_DATABASE=furtherance
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=furtherance
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    volumes:
      - furtherance_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  furtherance_data:
